"""Master QKD KMS schema

Revision ID: dc54ff972e34
Revises: 
Create Date: 2026-10-01 18:55:01.261066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc54ff972e34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qkd_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('key_material', sa.String(), nullable=False),
    sa.Column('slave_sae_id', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('AVAILABLE', 'RESERVED', 'CONSUMED', name='itemstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_qkd_keys_key_id'), 'qkd_keys', ['key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qkd_keys_key_id'), table_name='qkd_keys')
    op.drop_table('qkd_keys')
    # ### end Alembic commands ###
